# Generated by Django 4.2.1 on 2023-05-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_user_slug_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='link',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='dish-slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='adsd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='ssas'),
            preserve_default=False,
        ),
    ]
