# Generated by Django 4.2.1 on 2023-05-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_number',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.JSONField(default=dict),
        ),
    ]
