# Generated by Django 4.2.1 on 2023-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_restaurant_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurants',
            field=models.ManyToManyField(related_name='menus', to='menu.restaurant'),
        ),
    ]
