# Generated by Django 4.2.1 on 2023-05-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_category_options_remove_category_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(related_name='menus', to='menu.category'),
        ),
    ]
