# Generated by Django 4.2.1 on 2023-06-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menu_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu.restaurant'),
            preserve_default=False,
        ),
    ]
