# Generated by Django 4.2.1 on 2023-06-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_menu_categories_remove_menu_dishes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category'),
            preserve_default=False,
        ),
    ]
