# Generated by Django 4.2.1 on 2023-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_remove_category_dishes_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
